[tool.poetry]
name = "python-education"
version = "0.1.0"
description = ""
authors = ["Aleksandr S.Sakhatskii"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
psycopg2-binary = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
